version: '3.8'

services:
  payments:
    build:
      context: apps/payments
      args:
        user_id: ${DOCKER_UID:-1000}
        group_id: ${DOCKER_GID:-1000}
    volumes:
      # src
      - ./apps/payments/src/:/var/www/html/
      # config
      - ./config/payments/:/docker/config/
      # logs
      - ./logs/payments-apache-errors.log:/var/log/apache2/error.log
      - ./logs/payments-apache-access.log:/var/log/apache2/access.log
      - ./logs/payments-php-errors.log:/var/log/php/error.log
      - ./logs/payments-mw-debug.log:/var/log/php/mw-debug.log
      - ./logs/payments-xdebug.log:/var/log/xdebug.log
      - ./logs/payments-syslog.log:/var/log/syslog
    ports:
      - "8001:8000"
    environment:
      APACHE_RUN_USER: docker
      MW_SERVER: 'https://localhost:8001'
      MW_SCRIPT_PATH: ''
      MW_LOG_DIR: '/var/log/'
      MW_DB_TYPE: 'mysql'
      MW_DB_HOST: 'database'
      MW_DB_NAME: 'payments'
      MW_DB_USER: 'root'
      MW_DB_PASS: 'dockerpass'
      MW_LANG: 'en'
      MW_USER: 'admin'
      MW_PASS: 'dockerpass'
      MW_SITENAME: 'payments-wiki'
    depends_on:
      - database
      - queue
      - memcached

  civicrm:
    build:
      context: apps/civicrm
      args:
        user_id: ${DOCKER_UID:-1000}
        group_id: ${DOCKER_GID:-1000}
    volumes:
      # src
      - ./apps/civicrm/src/:/var/www/html/
      # logs
      - ./logs/civicrm-apache-errors.log:/var/log/apache2/error.log
      - ./logs/civicrm-apache-access.log:/var/log/apache2/access.log
      - ./logs/civicrm-php-errors.log:/var/log/php/error.log
      - ./logs/civicrm-xdebug.log:/var/log/xdebug.log
      - ./logs/civicrm-syslog.log:/var/log/syslog
    ports:
      - "8002:8002"
    environment:
      APACHE_RUN_USER: docker
    restart: unless-stopped
    depends_on:
      - database
      - queue
      - smashpig

  smashpig:
    build:
      context: apps/smashpig
      args:
        user_id: ${DOCKER_UID:-1000}
        group_id: ${DOCKER_GID:-1000}
    volumes:
      # src
      - ./apps/smashpig/src/:/var/www/html/
      # logs
      - ./logs/smashpig-apache-errors.log:/var/log/apache2/error.log
      - ./logs/smashpig-apache-access.log:/var/log/apache2/access.log
      - ./logs/smashpig-php-errors.log:/var/log/php/error.log
      - ./logs/smashpig-xdebug.log:/var/log/xdebug.log
      - ./logs/smashpig-syslog.log:/var/log/syslog
    ports:
      - "8003:8000"
    environment:
      APACHE_RUN_USER: docker
    depends_on:
      - database
      - queue

  civiproxy:
    build:
      context: apps/civiproxy
      args:
        user_id: ${DOCKER_UID:-1000}
        group_id: ${DOCKER_GID:-1000}
    volumes:
      # src
      - ./apps/civiproxy/src/proxy:/var/www/html/
      # logs
      - ./logs/civiproxy-apache-errors.log:/var/log/apache2/error.log
      - ./logs/civiproxy-apache-access.log:/var/log/apache2/access.log
      - ./logs/civiproxy-php-errors.log:/var/log/php/error.log
      - ./logs/civiproxy-xdebug.log:/var/log/xdebug.log
      - ./logs/civiproxy-syslog.log:/var/log/syslog
    ports:
      - "8004:8000"
    environment:
      APACHE_RUN_USER: docker
      CIVICRM_ADMIN_API_KEY: docker-api-key
      CIVICRM_SITE_KEY: civicrm-site-key
    depends_on:
      - civicrm

  queue:
    image: redis:5.0-buster
    volumes:
      - qdata:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  memcached:
    image: memcached

  database:
    image: mariadb:10.4
    volumes:
      - dbdata:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: dockerpass
    ports:
      - "33060:3306"

volumes:
  dbdata:
  qdata: